version: '3.3'
services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 0.5
    container_name: web
    environment:
      DOCUMENT_ROOT: html
    tty: true
    depends_on:
      - bdMysql
    volumes:
      - ./proyecto/:/var/www/html/proyecto/      
    ports:
      - 88:80
      - 2222:22
  bdMysql:
    image: mysql:latest
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 0.5
    container_name: bd
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${mysqlROOT}
      MYSQL_DATABASE: ${mysqlBD}
      MYSQL_USER: ${mysqlUSER}
      MYSQL_PASSWORD: ${mysqlPWD}
      TZ: America/Mexico_City
    volumes:
      - ./bd/:/docker-entrypoint-initdb.d      
    ports:
      - 3306:3306